controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

siteRoot:
    path: /
    controller: App\Controller\RootController::index

siteAjaxCardCreate:
    path: /ajaxform/create
    controller: App\Controller\AjaxFormController::create

siteAjaxCardGet:
    path: /ajaxform/get
    controller: App\Controller\AjaxFormController::get
